code_app/urls.py
from django.urls import include, path

from . import views

app_name = 'code'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('codeid/<int:code_id>', views.DetailView.as_view(), name='detail'),
    path('edit/<int:code_id>', views.EditView.as_view(), name='edit'),
    path('delete/<int:code_id>', views.DeleteView.as_view(), name='delete'),
    path('create/', views.CreateView.as_view(), name='create'),
    path('search/<str:tag>', views.SearchByTagView.as_view(), name='search'),
    path('all/', views.AllCodeView.as_view(), name='all'),
    path(
        'addcomment/<int:code_id>',
        views.CreateCommentView.as_view(),
        name='addcomment'),
    path(
        'updcomment/<int:comment_id>/<int:code_id>',
        views.UpdateCommentView.as_view(),
        name='updcomment'),
    path(
        'delcomment/<int:comment_id>/<int:code_id>',
        views.DeleteCommentView.as_view(),
        name='delcomment')
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('code_app.urls')),
    path('user/', include('user.urls'))
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/text/allcode.html
{% extends "templates.html" %}

{% block title %} All themes {% endblock %}

{% block content %}
<p style="text-align:center; font-weight:bold">Все темы</p>
<div class="table-responsive">
    <table class="table">
        <thead>
            <tr>
                <th>Тема</th>
                <th>Код</th>
                <th>Дата создания</th>
                <th>Дата изменения</th>
                <th>Автор</th>
            </tr>
        </thead>
        <tbody>
            {% for code in codes %}
                <tr>
                    <td>
                        <a href="{% url 'code:detail' code.id %}">
                            {{ code.topic }}
                        </a>
                    </td>
                    <td>{{ code.text|truncatewords:3 }}</td>
                    <td>{{ code.date_creation }}</td>
                    <td>{{ code.date_last_change }}</td>
                    <td>{{ code.user }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
<ul class="pagination">
    {% for i in codes.paginator.page_range %}
        <li {% if codes.number == i %}class="active"{% endif %}><a href="?page={{ i }}">{{ i }}</a></li>
    {% endfor %}
</ul>

{% endblock %}

templates/text/detail.html
{% extends "templates.html" %}

{% block title %} Code Detail {% endblock %}

{% block content %}
<div class="form-group">
    <label>Тема: </label>
    <p style="display:inline-block">{{ text.topic }}</p>
    <p>Код</p>
    <style type="text/css" media="screen">
        #editor {
            height: 400px;/*высота редактора*/
        }
    </style>
    <pre id="editor"></pre>
    <input id="code" type="hidden" value="{{ text.text }}">
    <script>
        var editor = ace.edit("editor");
        editor.session.setMode("ace/mode/python");
        code = document.getElementById("code").value;
        editor.session.setValue(code)
        editor.setOptions({
            readOnly:true,
            highlightActiveLine: false,
            selectionStyle: "text"
        });
    </script>
    <p style="font-weight:bold">
        Теги:
        {% for tag in tags %}
            {% if tag.tag != '' %}
                <a href="{%url 'code:search' tag.tag %}">{{ tag.tag }}</a>
            {% endif %}
        {% endfor %}
    </p>
    {% if request.user.is_authenticated %}
    <span style="color:rgb(115, 165, 206)">
        <i class="fas fa-file"></i>
    </span>
    <a href="{% url 'code:create' %}">Создать новый</a> |
        {% if text.user_id == request.user.id %}
            <span style="color:rgb(115, 165, 206)">
                <i class="fas fa-edit"></i>
            </span>
            <a href="{% url 'code:edit' text.id %}">Изменить</a> |
            <span style="color:rgb(115, 165, 206)">
                <i class="fas fa-trash-alt"></i>
            </span>
            <a href="{% url 'code:delete' text.id %}{{ url }}">Удалить</a>
        {% endif %}
    {% else %}
        <p class="text-danger">Авторизуйтесь, чтобы добавлять/изменять тексты</p>
    {% endif %}
</div>
<div class="comments form-group">
    <div class="add-comment form-group" id="add-comment">
        <label>Комментарии</label>
        {% if request.user.is_authenticated %}
        <form action="{% url 'code:addcomment' text.id %}" method="post">
            {% csrf_token %}
            <img src="{{request.user.avatar_or_default_url}}" style="width:60px; height:60px; border-radius: 60px; border: 2px solid #228f9a; display: inline-block;">
            <input id="comment-field" type="text" name="comment" class="form-control" style="display: inline-block; width: 80%;">
            <input type="hidden" name="reply_to" id="reply_to" value="">
            <input class="btn btn-primary" type="submit" value="Отправить" style="display: inline-block;">
            {% for error in form.comment.errors %}
                <p class="text-danger">{{ error }}</p>
            {% endfor %}
        </form>
        {% endif %}
    </div>
    <style>
        .comment {border-radius: 10px; border: 1px solid #228f9a; overflow: hidden; padding: 5px}
        .avatar, .name-comment {float: left;}
        .avatar {width: 6%;}
        .avatar img {width:60px; height:60px; border-radius: 60px; border: 2px solid #228f9a;}
        .name-comment {width: 55%;}
        .date, .buttons {width: 20%; float: right;}
        .comm {margin-top: 15px;}
        .buttons a{float: right; margin-right: 30px; margin-top: 20px;}
        @media only screen and (max-width:768px){
            .comment .name-comment{
                margin-left: 50px;
            }
            .buttons{
                display: block;
                width: 200px;
            }
        }
    </style>
    <div class="all-comments form-group">
        {% for comment in comments %}
        <div class="comment form-group" id="com{{comment.id}}">
            <div class="avatar">
                <img src="{{comment.user.avatar_or_default_url}}">
            </div>
            <div class="name-comment">
                <div class="name">
                    {{comment.user}}
                    {% if comment.reply_to %}
                        <p>В ответ: <a href="#com{{comment.reply_to.id}}">{{comment.reply_to.user.username}}</a></p>
                    {% endif %}
                </div>
                <div class="comm" id="{{comment.id}}comment" data-comment-id="{{comment.id}}" data-comment-name="{{comment.user}}">
                    <input type="hidden" value="{{comment.id}}" id="id-{{comment.id}}">
                    <p>{{comment.commentary}}</p>
                    <a style="color:#228f9a" href="#add-comment" onclick="reply($(this).closest('div').attr('id'))">Ответить</a>
                </div>
                <div class="edit-comm" id="{{comment.id}}editcomment" data-comment-id="{{comment.id}}" style="display:none">
                    <form action="{% url 'code:updcomment' comment.id text.id %}" method="post">
                        {% csrf_token %}
                        <input type="text" value="{{comment.comment}}" name="comment" class="form-control" style="width:500px; display:inline-block">
                        <input type="submit" value="Сохранить" class="btn btn-primary" style="display:inline-block">
                    </form>
                    <a href="javascript:void(0)" onclick="hideinput($(this).closest('div').attr('id'))">Отмена</a>
                </div>
            </div>
            <div class="date">
                Дата: {{comment.date_creation}}
            </div>
            <div class="buttons" id="{{comment.id}}edit" data-comment-id="{{comment.id}}">
                {% if request.user == comment.user %}
                <form action="{% url 'code:delcomment' comment.id text.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="Удалить" class="btn btn-danger btn-sm" style="float: right; margin-right: 30px;">
                    <input type="button" onclick="showinput($(this).closest('div').attr('id'))" value="Изменить" class="btn btn-primary btn-sm" style="float: right; margin-right: 5px;">
                </form>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </div>
</div>
<script>
    var doc = document;
    function showinput(comm_id)
    {
        var comment = doc.getElementById(comm_id);
        var id = comment.dataset.commentId;
        doc.getElementById(""+id+"comment").style.display = 'none';
        doc.getElementById(""+id+"editcomment").style.display = 'inline';
    }
    function hideinput(comm_id)
    {
        var comment = doc.getElementById(comm_id);
        var id = comment.dataset.commentId;
        doc.getElementById(""+id+"comment").style.display = 'block';
        doc.getElementById(""+id+"editcomment").style.display = 'none';
    }
    function reply(comm_id)
    {
        var comment = doc.getElementById(comm_id);
        var name = comment.dataset.commentName;
        var field = doc.getElementById('comment-field');
        field.value = name + ", ";
        var reply_to = doc.getElementById('reply_to');
        var id = comment.dataset.commentId;
        reply_to.value = id;
    }
</script>
{% endblock %}

templates/text/edit.html
{% extends "templates.html" %}

{% block title %} Code Detail {% endblock %}

{% block content %}
<label for="text">Изменить код:</label>
{% if error %}
<p style="color:red">{{ error }}</p>
{% endif %}
<style type="text/css" media="screen">
    #editor {
        height: 400px;/*высота редактора*/
    }
</style>
<input id="code" type="hidden" value="{{ text.text }}">
<form action="{% url 'code:edit' text.id %}" method="post">
    {% csrf_token %}
    <label>Тема</label>
    <div class="form-group">
        <input class="form-control" type="text" name="topic" value="{{ text.topic }}" required>
    </div>
    <label for="text">Изменить код:</label>
    <pre id="editor"></pre>
    <div class="ace-editor editor-control"></div>
    <label>Теги</label>
    <div class="form-group">
        <input id="input-tags" name="tags">
    </div>
    <input type="hidden" name="textfield" id="textfield" value="{{ text.text }}">
    <input class="btn btn-primary" type="submit" value="Изменить">
</form>
<script>
    var editor = ace.edit("editor");
    editor.session.setMode("ace/mode/python");
    code = document.getElementById("code").value;
    editor.setValue(code)
    function getcode(){
        var editor = ace.edit("editor");
        code = editor.getValue();
        return code
    }
    editor.session.on('change', function(delta) {
        $("#textfield").val(getcode());
    });
    $('#input-tags').selectize({
        delimiter: ',',
        persist: false,
        create: function(input) {
            return {
                value: input,
                text: input
            }
        }
    });
</script>
{% endblock %}

templates/text/tagsearch.html
{% extends "templates.html" %}

{% block title %} Search {% endblock %}

{% block content %}

<div>
    <p style="display: inline-block;">Тег: </p>
    <p style="display: inline-block; font-weight: bold;">{{ tag }}</p>
</div>
<div>
    <p style="display: inline-block;">Найдено совпадений: </p>
    <p style="display: inline-block; font-weight: bold;">{{ texts.count }}</p>
</div>
<div>
    {% for code in texts %}
        <p style="display: inline-block;">Тема: {{ code.text.topic }} |</p>
        <a style="display: inline-block;"href="{% url 'code:detail' code.text.id %}">Перейти</a><br>
    {% endfor %}
</div>


{% endblock %}

templates/text/templates.html
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="utf-8" />
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static "/bootstrap/css/bootstrap.min.css" %}"/>
    <script src="{% static "/bootstrap/js/bootstrap.min.js" %}"></script>
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="{% url 'text:index' %}">TextShare</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    {% if request.user.is_authenticated %}
                        <li><a href="{% url 'text:index' %}">Главная</a></li>
                        <li><a href="{% url 'text:create' %}">Создать</a></li>
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if request.user.is_authenticated %}
                        <li><p class="navbar-text">Добро пожаловать, {{ request.user }}</p></li>
                        <li><a href="{% url 'admin:logout' %}">Выйти</a></li>
                    {% else %}
                        <li><a href="{% url 'admin:login' %}">Войти</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
    <div id="maincontent" style="margin-top: 5%;">
        <div class="container">
            <div class="form-group">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
    <div class="footer" style="margin-top:10%;" >
        <div class="container">
            <p class="text-muted">Version 1.0</p>
        </div>
    </div>
</body>
</html>