code_app/urls.py
from django.urls import include, path

from . import views

app_name = 'code'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('codeid/<int:code_id>', views.DetailView.as_view(), name='detail'),
    path('edit/<int:code_id>', views.EditView.as_view(), name='edit'),
    path('delete/<int:code_id>', views.DeleteView.as_view(), name='delete'),
    path('create/', views.CreateView.as_view(), name='create'),
    path('search/<str:tag>', views.SearchByTagView.as_view(), name='search'),
    path('all/', views.AllCodeView.as_view(), name='all'),
    path(
        'addcomment/<int:code_id>',
        views.CreateCommentView.as_view(),
        name='addcomment'),
    path(
        'updcomment/<int:comment_id>/<int:code_id>',
        views.UpdateCommentView.as_view(),
        name='updcomment'),
    path(
        'delcomment/<int:comment_id>/<int:code_id>',
        views.DeleteCommentView.as_view(),
        name='delcomment')
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('code_app.urls')),
    path('user/', include('user.urls'))
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import include, path

from . import views

app_name = 'user'

urlpatterns = [
    path('create/', views.CreateView.as_view(), name='create'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogOutView.as_view(), name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('settings/', views.ProfileSettingsView.as_view(), name='settings'),
    path(
        'settings/setavatar',
        views.UpdateAvatarView.as_view(),
        name='setavatar'),
    path(
        'settings/setpass', views.UpdatePasswordView.as_view(), name='setpass')
]

templates/templates.html
{% load static %}
<!DOCTYPE html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial scale=1.0" />
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/png" href="{% static "img/logo.png" %}" />
    <script src="{% static "/bootstrap/js/jquery.js" %}"></script>
    <link rel="stylesheet" href="{% static "/bootstrap/css/bootstrap.min.css" %}"/>
    <script src="{% static "/bootstrap/js/bootstrap.min.js" %}"></script>
    <script src="{% static "ace/ace.js" %} "></script>
    <script src="{% static "selectize/js/standalone/selectize.js" %}"></script>
    <link rel="stylesheet" href="{% static "selectize/css/selectize.css" %}">
    <link rel="stylesheet" href="{% static "selectize/css/selectize.default.css" %}">
    <link rel="stylesheet" href="{% static "css/site.css" %}">
    <script src="{% static "js/site.js" %}" ></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
</head>
<body>
    <div style="border:none; border-radius: 0;"  class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-main">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a style="margin-top:-4px" class="navbar-brand" href="{% url 'code:index' %}">
                    <img style="display:inline-block" src="/static/logo.png">
                    <p style="display:inline-block">PythonShare</p>
                </a>
            </div>
            <div class="collapse navbar-collapse" id="navbar-main">
                <ul class="nav navbar-nav">
                    {% if request.user.is_authenticated %}
                        <li><a href="{% url 'code:index' %}">Главная</a></li>
                        <li><a href="{% url 'code:create' %}">Создать</a></li>
                        <li><a href="{% url 'code:all' %}">Темы</a></li>
                        <li><a href="{% url 'user:profile' %}">Профиль</a></li>
                    {% else %}
                        <li><a href="{% url 'code:index' %}">Главная</a></li>
                        <li><a href="{% url 'code:all' %}">Темы</a></li>
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if request.user.is_authenticated %}
                        <li><p class="navbar-text">Добро пожаловать, {{ request.user }}</p></li>
                        <li><a href="{% url 'user:logout' %}">Выйти</a></li>
                    {% else %}
                        <li><a href="{% url 'user:login' %}">Войти</a></li>
                        <li><a href="{% url 'user:create' %}">Регистрация</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
    <div class="footer">
        <div class="container">
            <p class="text-muted" style="text-align:center">Version 2.0 |<a href="https://github.com/sanyapalmero/PythonShare"> GitHub </a>| Telegram: @pa1m3r0</p>
        </div>
    </div>
</body>
</html>