code_app/urls.py
from django.urls import include, path

from . import views

app_name = 'code'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('codeid/<int:code_id>', views.DetailView.as_view(), name='detail'),
    path('edit/<int:code_id>', views.EditView.as_view(), name='edit'),
    path('delete/<int:code_id>', views.DeleteView.as_view(), name='delete'),
    path('create/', views.CreateView.as_view(), name='create'),
    path('search/<str:tag>', views.SearchByTagView.as_view(), name='search'),
    path('all/', views.AllCodeView.as_view(), name='all'),
    path(
        'addcomment/<int:code_id>',
        views.CreateCommentView.as_view(),
        name='addcomment'),
    path(
        'updcomment/<int:comment_id>/<int:code_id>',
        views.UpdateCommentView.as_view(),
        name='updcomment'),
    path(
        'delcomment/<int:comment_id>/<int:code_id>',
        views.DeleteCommentView.as_view(),
        name='delcomment')
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('code_app.urls')),
    path('user/', include('user.urls'))
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import include, path

from . import views

app_name = 'user'

urlpatterns = [
    path('create/', views.CreateView.as_view(), name='create'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogOutView.as_view(), name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('settings/', views.ProfileSettingsView.as_view(), name='settings'),
    path(
        'settings/setavatar',
        views.UpdateAvatarView.as_view(),
        name='setavatar'),
    path(
        'settings/setpass', views.UpdatePasswordView.as_view(), name='setpass')
]

user/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models
from django.utils import timezone

#Custom user model


class UserManager(BaseUserManager):
    def create_user(self, username, password, avatar, **kwargs):
        user = self.model(username=username, avatar=avatar, **kwargs)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password):
        user = self.model(username=username, role=User.ROLE_ADMIN)
        user.set_password(password)
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    objects = UserManager()
    USERNAME_FIELD = 'username'
    #REQUIRED_FIELDS = ['password']

    ROLE_USER = 'user'
    ROLE_ADMIN = 'admin'

    ROLE_CHOICES = [
        (ROLE_USER, "User"),
        (ROLE_ADMIN, "Admin"),
    ]

    username = models.CharField(max_length=20, unique=True)
    created_at = models.DateTimeField(default=timezone.now)
    role = models.CharField(
        max_length=64, choices=ROLE_CHOICES, default=ROLE_USER)
    avatar = models.FileField(null=True, upload_to='')

    @property
    def avatar_or_default_url(self):
        if not self.avatar:
            default_url = "/static/img/default.png"
            return default_url
        else:
            return self.avatar.url

    @property
    def is_superuser(self):
        return self.role == self.ROLE_ADMIN

    @property
    def is_staff(self):
        return self.role == self.ROLE_ADMIN

    def has_module_perms(self, app_label):
        return self.is_staff

    def has_perm(self, perm, obj=None):
        return self.is_staff

    def has_perms(self, perm_list, obj=None):
        return self.is_staff

    def get_full_name(self):
        return self.username

    def get_short_name(self):
        return self.username

user/forms.py
from django import forms

from . import models


class CreateUserForm(forms.Form):
    username = forms.CharField(label="Имя пользователя", max_length=20)
    password = forms.CharField(label="Пароль", max_length=128)
    repeat_password = forms.CharField(label="Повторите пароль", max_length=128)

    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            user = models.User.objects.get(username=username)
            error = 'Пользователь с таким именем уже существует!'
            self.add_error('username', error)
        except models.User.DoesNotExist:
            return username

    def clean(self):
        cleaned_data = super().clean()
        password = self.data.get('password')
        repeat_password = self.data.get('repeat_password')
        if password != repeat_password:
            error = 'Пароли не совпадают!'
            self.add_error('password', error)
            self.add_error('repeat_password', error)
        else:
            return cleaned_data


class LoginUserForm(forms.Form):
    username = forms.CharField(label="Ваше имя", max_length=20)
    password = forms.CharField(label="Пароль", max_length=128)

user/views.py
from code_app.models import Code
from code_app.views import add_log_entry

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.decorators import method_decorator
from django.views import View

from .forms import CreateUserForm
from .models import User


class CreateView(View):
    """Страница регистрации"""

    def get(self, request):
        template_name = 'user/register.html'
        form = CreateUserForm()
        return render(request, template_name, {'form': form})

    def post(self, request):
        template_name_login = 'user/login.html'
        template_name_register = 'user/register.html'

        form = CreateUserForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            repeat_password = form.cleaned_data['repeat_password']
            avatar = request.FILES.get('avatar')

            User.objects.create_user(username, password, avatar)
            success_registration = 'Вы успешно зарегистрированы!'
            return render(request, template_name_login,
                          {'success_registration': success_registration})
        else:
            return render(request, template_name_register, {'form': form})


class LoginView(View):
    """Страница авторизации"""

    def get(self, request):
        template_name = 'user/login.html'
        return render(request, template_name)

    def post(self, request):
        template_name = 'user/login.html'
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('code:index')
        else:
            failed_login = 'Неверное имя пользователя или пароль'
            add_log_entry(
                request, request.user,
                "Попытка авторизации. Неверное имя пользователя или пароль.")
            return render(request, template_name,
                          {'failed_login': failed_login})


class LogOutView(View):
    def get(self, request):
        logout(request)
        return redirect('code:index')


@method_decorator(login_required, name='dispatch')
class ProfileView(View):
    """Страница профиля пользователя"""
    ENTRIES_COUNT = 10

    def get(self, request):
        template_name = 'user/profile.html'
        user_codes = Code.objects.filter(user=request.user)
        paginator = Paginator(user_codes, self.ENTRIES_COUNT)
        page = request.GET.get('page')
        codes = paginator.get_page(page)
        return render(request, template_name, {
            'codes': codes,
            'all': user_codes
        })


@method_decorator(login_required, name='dispatch')
class ProfileSettingsView(View):
    """Страница настроек профиля"""

    def get(self, request):
        template_name = 'user/settings.html'
        return render(request, template_name)


@method_decorator(login_required, name='dispatch')
class UpdateAvatarView(View):
    def post(self, request):
        template_name = 'user/settings.html'
        user = get_object_or_404(User, username=request.user)
        avatar = request.FILES.get('avatar')

        if not avatar:
            no_file = "Файл не выбран"
            return render(request, template_name, {'no_file': no_file})
        else:
            user.avatar = avatar
            user.save()
            return redirect('user:profile')


@method_decorator(login_required, name='dispatch')
class UpdatePasswordView(View):
    def post(self, request):
        template_name_login = 'user/login.html'
        template_name_settings = 'user/settings.html'

        user = get_object_or_404(User, username=request.user)
        old_password = request.POST['old_password']
        new_password = request.POST['new_password']

        if user.check_password(old_password):
            user.set_password(new_password)
            user.save()

            success_change = "Пароль успешно был изменен, авторизуйтесь снова."
            add_log_entry(request, request.user, "Успешное изменение пароля")
            return render(request, template_name_login,
                          {'success_change': success_change})
        else:
            passwords_not_matched = "Пароли не совпадают!"
            add_log_entry(request, request.user,
                          "Попытка изменения пароля: пароли не совпадают")
            return render(request, template_name_settings,
                          {'passwords_not_matched': passwords_not_matched})

templates/user/login.html
{% extends "templates.html" %}

{% block title %} Login {% endblock %}

{% block content %}
    <h3>Авторизация</h3>
    <form action="{% url 'user:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label>Имя пользователя</label>
            <input style="width:250px;" type="text" class="form-control" name="username">
        </div>
        <div class="form-group">
            <label>Пароль</label>
            <input style="width:250px;" type="password" class="form-control" name="password">
        </div>
        <input class="btn btn-primary" type="submit" value="Войти">
    </form>
    {% if success_change %}
        <p style="color:green">{{ success_change }}</p>
    {% endif %}
    {% if success_registration %}
        <p style="color:green">{{ success_registration }}</p>
    {% endif %}
    {% if failed_login %}
        <p style="color:red">{{ failed_login }}</p>
    {% endif %}
{% endblock %}

templates/user/profile.html
{% extends "templates.html" %}

{% block title %} Profile {% endblock %}

{% block content %}

<div class="row">
    <div class="col-md-4">
        <a href="{% url 'user:settings' %}">Настройки профиля</a>
    </div>
    <div class="col-md-4" style="text-align:center;">
        <p style="font-weight:bold;">{{request.user}}</p>
        <img src="{{request.user.avatar_or_default_url}}" style="width:100px; height:100px; border-radius: 100px; border: 3px solid #228f9a;">
        <p>Количество созданных тем: {{ all.count }}</p>
    </div>
</div>
<p style="text-align:center; font-weight:bold">Ваш код</p>
<table class="table">
    <thead>
        <tr>
            <th>Тема</th>
            <th>Код</th>
            <th>Дата создания</th>
            <th>Дата изменения</th>
        </tr>
    </thead>
    <tbody>
        {% for code in codes %}
            <tr>
                <td>
                    <a href="{% url 'code:detail' code.id %}?next={{ request.get_full_path|urlencode }}">
                        {{ code.topic }}
                    </a>
                </td>
                <td>
                    {{ code.code|truncatewords:3 }}
                </td>
                <td>{{ code.date_creation }}</td>
                <td>{{ code.date_last_change }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
<ul class="pagination">
    {% for i in codes.paginator.page_range %}
        <li {% if codes.number == i %}class="active"{% endif %}><a href="?page={{ i }}">{{ i }}</a></li>
    {% endfor %}
</ul>

{% endblock %}

templates/user/register.html
{% extends "templates.html" %}

{% block title %} Registration {% endblock %}

{% block content %}
<h3>Регистрация</h3>
<form action="{% url 'user:create' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
        <label>Имя пользователя</label>
        <input style="width:250px;" type="text" class="form-control" name="username" value="{{ form.username.value|default_if_none:'' }}">
        {% for error in form.username.errors %}
            <p class="text-danger">{{ error }}</p>
        {% endfor %}
    </div>
    <div class="form-group">
        <label>Пароль</label>
        <input style="width:250px;" type="password" class="form-control" name="password" value="{{ form.password.value|default_if_none:'' }}">
        {% for error in form.password.errors %}
            <p class="text-danger">{{ error }}</p>
        {% endfor %}
    </div>
    <div class="form-group">
        <label>Повторите пароль</label>
        <input style="width:250px;" type="password" class="form-control" name="repeat_password" value="{{ form.repeat_password.value|default_if_none:'' }}">
        {% for error in form.repeat_password.errors %}
            <p class="text-danger">{{ error }}</p>
        {% endfor %}
    </div>
    <div class="form-group">
        <label>Аватар</label>
        <input type="file" name="avatar">
        {% for error in form.avatar.errors %}
            <p class="text-danger">{{ error }}</p>
        {% endfor %}
    </div>
    <input class="btn btn-primary" type="submit" value="Зарегистрироваться">
</form>
{% endblock %}

templates/user/settings.html
{% extends "templates.html" %}

{% block title %} Settings {% endblock %}

{% block content %}
<p style="text-align:center; font-weight:bold;">Настройки профиля {{request.user}}</p>
<div class="row">
    <div class="col-md-4">
        <p style="font-weight:bold;">Аватар:</p>
        <img src="{{request.user.avatar_or_default_url}}" style="width:100px; height:100px; border-radius: 100px; border: 3px solid #228f9a;">
        <form style="margin-top:10px" action="{% url 'user:setavatar' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <input type="file" name="avatar">
                {% for error in form.avatar.errors %}
                    <p class="text-danger">{{ error }}</p>
                {% endfor %}
            </div>
            <input class="btn btn-primary" type="submit" value="Обновить аватар">
        </form>
        {% if no_file %}
            <p style="color:red">{{ no_file }}</p>
        {% endif %}
    </div>
    <div class="col-md-4">
        <p style="font-weight:bold;">Смена пароля</p>
        <form action="{% url 'user:setpass' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label>Старый пароль</label>
                <input style="width:250px;" type="password" class="form-control" name="old_password">
                {% if passwords_not_matched %}
                    <p style="color:red">{{ passwords_not_matched }}</p>
                {% endif %}
            </div>
            <div class="form-group">
                <label>Новый пароль</label>
                <input style="width:250px;" type="password" class="form-control" name="new_password">
            </div>
            <input class="btn btn-primary" type="submit" value="Изменить пароль">
        </form>
    </div>
    <div class="col-md-4">
        <p style="font-weight:bold;">Информация</p>
        <p>Дата регистрации {{ request.user.created_at }}</p>
    </div>
</div>
{% endblock %}